// ============================================================
// wgt_bram.v
// Single-port weight+bias BRAM (read-only after init).
// Initialised from a hex file generated by the Python notebook.
// ============================================================
module wgt_bram #(
    parameter DATA_WIDTH = 8,
    parameter DEPTH      = 256,   // override per layer
    parameter INIT_FILE  = ""     // must be set per instance
)(
    input  wire                      clk,
    input  wire [$clog2(DEPTH)-1:0]  addr,
    output reg  [DATA_WIDTH-1:0]     dout
);
    (* rom_style = "block" *)
    reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];

    initial begin
        if (INIT_FILE != "") $readmemh(INIT_FILE, mem);
    end

    always @(posedge clk) begin
        dout <= mem[addr];
    end
endmodule